In [2]:
import numpy as np
import random
n=5

nodes = np.arange(n)
tri = np.random.choice(nodes, size=3, replace=False)

# n=5 d=3
tris = np.random.choice(nodes, size=(5, 3), replace=True)
print('nodes:', nodes)
print('tri:', tri, type(tri))
print('tris:', tris)
print('tris_shape:', tris.shape)
print('type of tris:', type(tris))


tri.sort()
print('sorted triangle:', tri)


tri1 = np.random.choice(nodes, size=3, replace=False)
tri2 = np.random.choice(nodes, size=3, replace=False)

states = np.zeros(n, dtype=int)
states1 = np.array([0, 0, 0, 0, 0])
states[tri] = 1
states1[[1, 2, 3]] = 1
print('states:', states, type(states))
print('states1:', states1)

tri1.sort()
tri2.sort()

batch = []
batch.append(tuple(tri.tolist()))
print('tri_tolist:', tri.tolist())
print("tuple(tri.tolist()):", tuple(tri.tolist()))
print('batch:', batch)

batch.append(tuple(tri1.tolist()))
batch.append(tuple(tri2.tolist()))

print('batch_all:', batch)

edges_set = set()
edges_set.add(tuple(tri.tolist()))
print('edges_set:', edges_set)


hyperedges = np.array(list(edges_set), dtype=int)
print("list(edges_set):", list(edges_set))
print("np.array(list(edges_set)):", hyperedges, type(hyperedges))


nodes: [0 1 2 3 4]
tri: [1 4 2] <class 'numpy.ndarray'>
tris: [[3 3 4]
 [4 4 4]
 [2 3 2]
 [1 4 4]
 [3 1 4]]
tris_shape: (5, 3)
type of tris: <class 'numpy.ndarray'>
sorted triangle: [1 2 4]
states: [0 1 1 0 1] <class 'numpy.ndarray'>
states1: [0 1 1 1 0]
tri_tolist: [1, 2, 4]
tuple(tri.tolist()): (1, 2, 4)
batch: [(1, 2, 4)]
batch_all: [(1, 2, 4), (0, 1, 3), (1, 2, 3)]
edges_set: {(1, 2, 4)}
list(edges_set): [(1, 2, 4)]
np.array(list(edges_set)): [[1 2 4]] <class 'numpy.ndarray'>


In [3]:
a = len(np.unique(tri1))
print(a)
print(tris.shape[0])

3
5


In [4]:
#numpy数组索引 与 Python列表索引

# 关键在于 [2 0 1] 是numpy数组的显示格式（创建时仍需np.array([2, 0, 1])）
# [1, 2, 3] 是Python列表的代码格式（必须用逗号）

import numpy as np

n = 5
states = np.zeros(n, dtype=int)
states1 = np.zeros(n, dtype=int)
states2 = np.zeros(n, dtype=int)

# 方式1：使用numpy数组索引
index_array = np.array([1, 2, 3])
states[index_array] = 1
print("index_array:", index_array)

# 方式2：使用Python列表索引  
index_list = [1, 2, 3]
states1[index_list] = 1
print("index_list:", index_list)

states2[([1, 2, 3])] = 1
states2[[1, 2, 3]] = 1

print("numpy数组索引结果:", states)    # [0 1 1 1 0]
print("Python列表索引结果:", states1)  # [0 1 1 1 0]
print("Python列表索引结果:", states2)  # [0 1 1 1 0]
print("结果相同:", np.array_equal(states, states1))  # True

index_array: [1 2 3]
index_list: [1, 2, 3]
numpy数组索引结果: [0 1 1 1 0]
Python列表索引结果: [0 1 1 1 0]
Python列表索引结果: [0 1 1 1 0]
结果相同: True


数据类型对比

In [5]:
import numpy as np

tri = np.array([2, 5, 1])  # numpy数组
tri.sort()  # 排序后: [1, 2, 5]

result1 = tri.tolist()        # 转换为Python列表
result2 = tuple(tri.tolist()) # 转换为元组

print("tri:", tri, type(tri))
# tri: [1 2 5] <class 'numpy.ndarray'>

# 过程：numpy数组 → 元组
print("tuple(tri):", tuple(tri), type(tuple(tri)))
# tuple(tri): (1, 2, 5) <class 'tuple'>

# 列表 (list) - 不可哈希
print("tri.tolist():", result1, type(result1)) 
# tri.tolist(): [1, 2, 5] <class 'list'>

# 元组 (tuple) - 可哈希
# 过程：numpy数组 → Python列表 → 元组
print("tuple(tri.tolist()):", result2, type(result2))
# tuple(tri.tolist()): (1, 2, 5) <class 'tuple'>


tri: [1 2 5] <class 'numpy.ndarray'>
tuple(tri): (1, 2, 5) <class 'tuple'>
tri.tolist(): [1, 2, 5] <class 'list'>
tuple(tri.tolist()): (1, 2, 5) <class 'tuple'>


In [6]:
import math

edges_set = set()   
tri = np.random.choice(nodes, size=3, replace=False)
tri = np.sort(tri)
# 因为numpy数组不可哈希，不能直接添加到集合中。需要将数组转换为可哈希的类型
# edges_set.add(tri)

edges_set.add(tuple(tri))
hyperedges = list(edges_set)
print('hyperedges:',hyperedges)

hyperedges: [(1, 3, 4)]


In [7]:
deg = np.zeros(n, dtype=int)
print("deg:", deg )
for (i,j,k) in hyperedges:
        deg[i] += 1
        deg[j] += 1
        deg[k] += 1

print("deg:", deg )

deg: [0 0 0 0 0]
deg: [0 1 0 1 1]


In [8]:
import numpy as np

# 假设有7个节点
n = 7
states = np.array([1, 0, 1, 0, 0, 0, 0])  # 节点状态: 0=S, 1=I
print("节点状态:", states)  # [1 0 1 0 0 0 0]

# 超边数组 (4个超边，每个3个节点)
hyperedges = np.array([
    [0, 1, 2],  # 超边1: 节点0,1,2
    [1, 3, 4],  # 超边2: 节点1,3,4  
    [2, 5, 6],  # 超边3: 节点2,5,6
    [0, 3, 5]   # 超边4: 节点0,3,5
])
print("超边0:")
print(hyperedges[0])
print("超边:")
print(hyperedges)

# 关键操作：获取每个超边中节点的状态
states_per_edge = states[hyperedges]

states_per_edge1 = states[[0, 1, 2]] 
states_per_edge1 = states[([0, 1, 2])] 
print("\n每个超边中节点的状态:")
print(states_per_edge)

print("\n超边1中节点的状态:")
print(states_per_edge1)

inf_counts = states_per_edge.sum(axis=1)
print("\n每个超边中感染节点的数量:")
print(inf_counts)

节点状态: [1 0 1 0 0 0 0]
超边0:
[0 1 2]
超边:
[[0 1 2]
 [1 3 4]
 [2 5 6]
 [0 3 5]]

每个超边中节点的状态:
[[1 0 1]
 [0 0 0]
 [1 0 0]
 [1 0 0]]

超边1中节点的状态:
[1 0 1]

每个超边中感染节点的数量:
[2 0 1 1]


In [9]:
import numpy as np

# 假设有5个超边，每个超边的感染节点数
inf_counts = np.array([2, 0, 2, 1, 3])  # 形状: (5,)
print("每个超边的感染节点数:", inf_counts)  # [2 0 2 1 3]

# 找到感染节点数恰好为2的超边
mask = inf_counts == 2
print("布尔掩码:", mask)  # [ True False  True False False]

# 使用np.where
result_tuple = np.where(inf_counts == 2)
print("np.where返回:", result_tuple)  # (array([0, 2]),)

# 提取索引数组
candidates = result_tuple[0]
print("候选超边索引:", candidates)  # [0 2]

print("第一个候选超边", candidates[0]) # 0

states = np.array([1 , 1, 0])

print("states[candidates]", states[candidates])
print("states[candidates[0]]", states[candidates[0]])


每个超边的感染节点数: [2 0 2 1 3]
布尔掩码: [ True False  True False False]
np.where返回: (array([0, 2], dtype=int64),)
候选超边索引: [0 2]
第一个候选超边 0
states[candidates] [1 0]
states[candidates[0]] 1


In [10]:
# 1018——test 的测试代码

# 超边列表
hyperedges = np.array([
    [1,2,3],
    [2,4,5],
    [1,3,6]
])  

# 边列表
edges = hyperedges



n = 7  # 节点数
m = hyperedges.shape[0]

# --- 构建每个节点对应的超边列表（邻接信息） ---
node_edge_pos = [[] for _ in range(n)]
print("node_edge_pos: ", node_edge_pos)
for ei in range(m):
    a,b,c = edges[ei]
    print("ei: ", ei, "a: ", a, "b: ", b, "c: ", c)
    node_edge_pos[a].append((ei,0))
    print("node_edge_pos[a]: ", node_edge_pos[a])
    node_edge_pos[b].append((ei,1))
    print("node_edge_pos[b]: ", node_edge_pos[b])
    node_edge_pos[c].append((ei,2))
    print("node_edge_pos[c]: ", node_edge_pos[c])

print("node_edge_pos: ", node_edge_pos)
'''
说明 
node_edge_pos:  [[], [(0, 0), (2, 0)], [(0, 1), (1, 0)], [(0, 2), (2, 1)], [(1, 1)], [(1, 2)], [(2, 2)]]
节点0: []                   # 不参与任何超边
节点1: [(0,0), (2,0)]       # 在超边0的位置0  在超边2的位置0
节点2: [(0,1), (1,0)]       # 在超边0的位置1  在超边1的位置0
节点3: [(0,2), (2,1)]       # 在超边0的位置2  在超边2的位置1
节点4: [(1,1)]              # 在超边1的位置1
节点5: [(1,2)]              # 在超边1的位置2
节点6: [(2,2)]              # 在超边2的位置2
'''
print("------------------------------------------")
# 节点列表 第一列
edge_i = edges[:,0]
print("edge_i: ", edge_i)

p = np.full(n, 0.3, dtype=float)  # 初始感染概率
print("p: ", p)
p_i = p[edge_i]
print("p_i: ", p_i)

Q = np.ones(n, dtype=float)  # 初始节点活跃度
print("Q: ", Q)

node_edge_pos:  [[], [], [], [], [], [], []]
ei:  0 a:  1 b:  2 c:  3
node_edge_pos[a]:  [(0, 0)]
node_edge_pos[b]:  [(0, 1)]
node_edge_pos[c]:  [(0, 2)]
ei:  1 a:  2 b:  4 c:  5
node_edge_pos[a]:  [(0, 1), (1, 0)]
node_edge_pos[b]:  [(1, 1)]
node_edge_pos[c]:  [(1, 2)]
ei:  2 a:  1 b:  3 c:  6
node_edge_pos[a]:  [(0, 0), (2, 0)]
node_edge_pos[b]:  [(0, 2), (2, 1)]
node_edge_pos[c]:  [(2, 2)]
node_edge_pos:  [[], [(0, 0), (2, 0)], [(0, 1), (1, 0)], [(0, 2), (2, 1)], [(1, 1)], [(1, 2)], [(2, 2)]]
------------------------------------------
edge_i:  [1 2 1]
p:  [0.3 0.3 0.3 0.3 0.3 0.3 0.3]
p_i:  [0.3 0.3 0.3]
Q:  [1. 1. 1. 1. 1. 1. 1.]


In [11]:
# 1021_MCfinal 测试代码
R = 5
T = 3
rho_runs = np.zeros((R, T+1), dtype=float)
print("rho_runs: ", rho_runs)

rho_runs:  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# 1022_test1 测试代码
n = 10
d = 3
rng = np.random.default_rng(seed=42)  # 创建独立随机数生成器
nodes = rng.choice(n, size=(d,), replace=False)
print("nodes:",nodes) # 输出一直是[9 0 6]可复现

nodes1 = np.random.choice(n, size=(d,), replace=False)
print("nodes1:",nodes1)

nodes: [9 0 6]
nodes1: [7 6 0]
